#! /usr/bin/env bash
set -eu

function args.assert.single() {
  if [[ $# -ne 1 ]]; then
    echo "ERROR: Expected a single argument!"
    return 2
  fi
}

function args.assert.double() {
  if [[ $# -ne 2 ]]; then
    echo "ERROR: Expected two arguments!"
    return 2
  fi
}
