#! /usr/bin/env bash
#set -euo pipefail
. include "args"
# Public API
# file.is.present $file_name
# file.is.absent $file_name
# file.has.perms $perms $file_name
# file.has.owner $owner:group $filename
# file.assert.size $size $file_name

function file.assert.present() {
  args.assert.single "$@"
  test -f "$1"
}
function file.assert.absent() {
  args.assert.single  "$@"
  ! file.assert.present "$1"
}

function file.is.present() {
  args.assert.single  "$@"
  file_name="$1"
  if file.assert.absent "$file_name" ; then
    touch "$file_name"
  fi
  file.assert.present "$file_name"
}
function file.is.absent() {
  args.assert.single  "$@"
  file_name="$1"
  if file.assert.present "$file_name" ; then
    rm -f "$file_name"
  fi
  file.assert.absent "$file_name"
}

function file.assert.perms() {
  args.assert.double "$@"
  test $(stat --format '%a' "$2") == "$1"
}
function file.has.perms() {
  if ! file.assert.perms "$1" "$2" ; then
    chmod "$1" "$2"
  fi
  file.assert.perms "$1" "$2"
}

function file.assert.owner() {
  args.assert.double "$@"
  test $(stat --format '%U:%G' "$2") == "$1"
}
function file.has.owner() {
  args.assert.double "$@"
  if ! file.assert.owner "$1" "$2" ; then
    (set -x; chown "$1" "$2")
  fi
  file.assert.owner "$1" "$2"
}

function file.assert.line() {
  args.assert.double "$@"
  LINE="$1"
  FILE="$2"
  grep --fixed-strings --line-regexp --quiet "$LINE" "$FILE"
}
function file.assert.line_match() {
  args.assert.double "$@"
  MATCH="$1"
  FILE="$2"
  grep --quiet "$MATCH" "$FILE"
}
function file.has.line() {
  MATCH="$1"
  LINE="$2"
  FILE="$3"
  if file.assert.line "$LINE" "$FILE" ; then
    return 0;
  fi

  if file.assert.line_match "$MATCH" "$FILE" ; then
    (set -x; sed -i "/$MATCH/ c $LINE" "$FILE")
  else
    (set -x; echo "$LINE" >> "$FILE")
  fi
  file.assert.line "$LINE" "$FILE"
}

function stat_size() {
  args.assert.single "$@"
  stat --format='%s' $1
}
function file.assert.size() {
  args.assert.double "$@"
  SIZE="$1"
  NAME="$2"
  if file.assert.present "${NAME}" ; then
    test "$(stat_size ${NAME})" == "$(numfmt --from=iec ${SIZE})"
  else
    return 1
  fi
}
