#! /usr/bin/env bash
#set -euo pipefail
. include "args"
# Public API
# apt.installed pkg [pkg...]
# apt.removed pkg [pkg...]

function user.assert.added() {
  args.assert.single "$@"
  id -u "$1" &>/dev/null
}

function user.is.added() {
  args.assert.single  "$@"
  user_name="$1"
  if user.assert.removed "$user_name" ; then
    sudo useradd -d "/home/${user_name}" -s /bin/bash -m "$user_name"
  fi
  user.assert.added "$user_name"
}

function user.assert.removed() {
  args.assert.single  "$@"
  ! user.assert.added "$1"
}

function user.is.removed() {
  args.assert.single  "$@"
  user_name="$1"
  if user.assert.added "$user_name" ; then
    sudo userdel "$user_name"
  fi
  user.assert.removed "$user_name"
}
